# Generated by Django 5.1.7 on 2025-03-24 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_education_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Asile Ayuba", max_length=100)),
                ("profile_image", models.ImageField(upload_to="profile_images/")),
                ("resume", models.FileField(upload_to="resumes/")),
            ],
        ),
    ]
