# Generated by Django 5.1.7 on 2025-03-25 05:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0007_alter_home_profile_image_alter_profile_profile_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="resume",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="file"
            ),
        ),
    ]
