# Generated by Django 5.1.7 on 2025-03-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_alter_profile_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="resume",
            field=models.FileField(upload_to="resumes/"),
        ),
    ]
