# Generated by Django 5.1.7 on 2025-06-19 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_alter_profile_resume"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="resume",
        ),
    ]
